### ISSUE TITLE
Remove set-output from workflows in atsign-foundation and atsign-company GitHub Actions workflows.

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/.github#42]
### Is your feature request related to a problem? Please describe.

`set-output` has been deprecated by GitHub, leading to warnings in Actions:

![image](https://user-images.githubusercontent.com/478926/203756200-68734856-35c7-4d92-88b2-d7f83b7e8fde.png)

### Describe the solution you'd like

Update workflows that use `set-output` to make use of alternative `$GITHUB_OUTPUT` mechanism.

[How to Patch the Deprecated set-output in GitHub Workflows and in Container Actions](https://dev.to/cicirello/how-to-patch-the-deprecated-set-output-in-github-workflows-and-in-container-actions-9co) provides guidance for the set-output changes needed. 

[atsign-company/at_dockerfiles#66](https://github.com/atsign-company/at_dockerfiles/pull/66) provides an example of a workflow where this has already been done.

Whilst updating the workflows please also run them through the [StepSecurity Secure Workflow](https://app.stepsecurity.io/secureworkflow) to constrain token permissions and pin dependencies.

**Comment by kumarnarendra701** [comment]
@cpswan -Fixed this issue - https://github.com/atsign-company/at_find_api/actions/runs/3619329473

Fixed version - https://github.com/atsign-company/at_find_api/actions/runs/3636856643

**Comment by cpswan** [comment]
@kumarnarendra701 is that the only instance of the problem across both orgs?

Also I asked for the workflow to be updated with pinned dependencies and constrained token permissions, which hasn't been done.

**Comment by cpswan** [comment]
Multiple pinned dependency PRs have now been created and approved.
