### ISSUE TITLE
Sprint Board Migration

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/.github#52]
- [x] Propose the [intended changes](https://gist.github.com/XavierChanth/c18d9e67e0cfb6d5a2419af5f22fa13b) with the team
- [x] Migrate necessary `Priority` items to `Type`
- [x] Migrate SP and PR (after PR53 planning)
- [x] Migrate necessary `Status` items to `Type`
- [x] Add the [new views](https://github.com/users/XavierChanth/projects/4/views/31)
- [x] Teach the team how to use the new views effectively
- [x] Update [reminder](https://docs.google.com/document/d/1wrA_d_xyV60C_sYd1eFEvfpETa1UcFjid4pfCs3p8AM/edit) @ksanty
- [x] Update Planning Poker Export Scripts @XavierChanth 
- [x] Simplify `Status` items (removing certain fields)
- [x] Remove the old views
- [x] Update GItHub [readme](https://docs.google.com/document/d/1oa5QQBaO8nm9_HQjQNwk97MNm47HpuRZPgZ4AhuPhGQ/edit)

**Comment by ksanty** [comment]
@XavierChanth the team ran a smooth sprint this morning/evening.  I did my best to start mapping in existing cards to the new structure to save some time.  Feel free to keep me updated and I will continue doing what I can.  I also want to update documentation and we should get it posted to the repo I think you created.  Which repo is it?

**Comment by xavierchanth** [comment]
The repo I made is [atsign-foundation/community](https://github.com/atsign-foundation/community) but I think the documentation for this may better fit into [atsign-foundation/.github](https://github.com/atsign-foundation/.github).

**Comment by xavierchanth** [comment]
The only remaining work is to document the new board, which is captured in #54.
