### ISSUE TITLE
Sprint-planning docs

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/.github#54]
### Is your feature request related to a problem? Please describe.

Add a docs item explaining the sprint planning process so that we can remove some of the biweekly sprint prep messaging.

### Describe the solution you'd like

-

**Comment by ksanty** [comment]
Here's [what I started](https://docs.google.com/document/d/17CbTh4Q5RT2IS1ZOdhr5r98q6KTcVMdXsgNrlYfSsjw/edit) a while back

**Comment by xavierchanth** [comment]
@ksanty if you have time, could you finish converting that to the markdown file you started and raise a PR?

**Comment by ksanty** [comment]
> @ksanty if you have time, could you finish converting that to the markdown file you started and raise a PR?

Sure! Here it is https://github.com/atsign-foundation/.github/pull/77
